# https://github.com/18F/github-action-eslint
name: Lint

on: [push]

jobs:
  eslint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: 18F/github-action-eslint@1.0.0
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
